---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
configurations:
  - .transformers.yaml
generators:
  - .ksops.yaml
namespace: "copilot-ops"
patchesStrategicMerge:
  - route.yaml
images:
  - name: controller
    newName: "quay.io/copilot-ops/copilot-ops-bot"
    newTag: latest 