---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: controller
spec:
  secretStoreRef:
    name: opf-vault-store
    kind: SecretStore
  target:
    name: controller
  dataFrom:
    - extract:
        key: moc/smaug/copilot-ops/data
