---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: copilot-ops
spec:
  params:
    - name: REPO_NAME
      type: string
      default: ".github"
    - name: CONTEXT
      type: string
      default: ""
    - name: SECRET_NAME
      type: string
  steps:
    - name: copilot-ops
      image: localhost/copilot-ops/copilot-ops
      volumeMounts:
        - mountPath: /mnt/secret
          name: github-token
      env:
        - name: ORG_NAME
          valueFrom:
            secretKeyRef:
              name: $(params.SECRET_NAME)
              key: orgName
        - name: APP_ID
          valueFrom:
            secretKeyRef:
              name: copilot-ops
              key: app_id
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.SECRET_NAME)
              key: token
      command: ["/bin/bash"]
      args:
        - "-c"
        - |
          #!/bin/sh

          # Clone repository
          echo "Cloning repository..."
          git clone https://x-access-token:$GITHUB_TOKEN@github.com/$ORG_NAME/$(params.REPO_NAME)
          cd $(params.REPO_NAME)

          echo "Context: $(params.CONTEXT)"
          # Run Copilot-ops on the repository
          /copilot-ops --help

          # octokit.createPullRequest()

  volumes:
    - name: github-token
      secret:
        secretName: $(params.SECRET_NAME)
        items:
          - key: token
            path: token
        optional: false
