---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- copilot-ops.yaml
configurations:
- .transformers.yaml
namePrefix: "copilot-ops-bot-"
commonLabels:
  app.kubernetes.io/component: task
images:
- name: copilot-ops
  newName: quay.io/copilot-ops/copilot-ops:latest
